from enum import Enum


class AllureTags(str, Enum):
    AUTHORIZATION = 'AUTHORIZATION'
    COURSES = 'COURSES'
    DASHBOARD = 'DASHBOARD'
    NAVIGATION = 'NAVIGATION'
    REGISTRATION = 'REGISTRATION'
    REGRESSION = 'REGRESSION'
    USER_LOGIN = 'USER_LOGIN'
